export const houses = [
  {
    image: "/img/listings/venice.jpg",
    address: "139 Venice Lane",
    city: "Thermal",
    state: "CA",
    zip: "92274",
    price: "$315,000",
    beds: 3,
    baths: 3,
    sqft: "3,070",
    status: "Closed",
    property: "House",
  },
  {
    image: "/img/listings/leto.jpg",
    address: "2870 Leto Avenue",
    city: "Thermal",
    state: "CA",
    zip: "92274",
    price: "$10,000",
    sqft: "11,015",
    status: "Closed",
    property: "Lot",
  },
  {
    image: "/img/listings/balboa.jpg",
    address: "56 Balboa Avenue",
    city: "Thermal",
    state: "CA",
    zip: "92274",
    price: "$15,000",
    sqft: "6,949",
    status: "Closed",
    property: "Lot",

  },
  {
    image: "/img/listings/market.jpg",
    address: "0 Market Street",
    city: "Thermal",
    state: "CA",
    zip: "92274",
    price: "$45,000",
    sqft: "5,663",
    status: "Closed",
    property: "Lot",

  },
  {
    image: "/img/listings/tramonto.jpg",
    address: "84255 Tramonto Way",
    city: "Indio",
    state: "CA",
    zip: "92203",
    price: "$510,000",
    beds: 3,
    baths: 2,
    sqft: "1,637",
    status: "Closed",
    property: "House",

  },
  {
    image: "/img/listings/avenue64.jpg",
    address: "88961 Avenue 64",
    city: "Thermal",
    state: "CA",
    zip: "92274",
    price: "$650,000",
    beds: 2,
    baths: 1,
    sqft: "261,360",
    status: "Closed",
    property: "House",

  },
  {
    image: "/img/listings/leeward.jpg",
    address: "0 Leeward Drive",
    city: "Mecca",
    state: "CA",
    zip: "92254",
    price: "$25,000",
    sqft: "7,405",
    status: "Closed",
    property: "Lot",

  },
  {
    image: "/img/listings/cottonwood.jpg",
    address: "0 Cottonwood Drive",
    city: "Desert Hot Springs",
    state: "CA",
    zip: "92241",
    price: "$55,000",
    sqft: "10,890",
    status: "Closed",
    property: "Lot",

  },
  {
    image: "/img/listings/avila.jpg",
    address: "52754 Calle Avila",
    city: "Coachella",
    state: "CA",
    zip: "92236",
    price: "$220,000",
    beds: 3,
    baths: 2,
    sqft: "1,008",
    status: "Closed",
    property: "House",

  },
  {
    image: "/img/listings/brown.jpg",
    address: "80838 Brown Street",
    city: "Indio",
    state: "CA",
    zip: "92201",
    price: "$450,000",
    baths: 2,
    beds: 3,
    sqft: "1,261",
    status: "Closed",
    property: "House",
  },
  {
    image: "/img/listings/grapefruit.jpg",
    address: "0 Grapefruit Boulevard",
    city: "Thermal",
    state: "CA",
    zip: "92274",
    price: "$97,000",
    sqft: "5,662",
    status: "Active",
    property: "Lot",

  },
];

